"""Ports (DIP) — documented boundaries for exchange use-cases."""
from __future__ import annotations

from typing import Protocol

from ..models import BookExchangeRequest, CustomUser, LoanHandoff, Shelf


class ExchangeNotifier(Protocol):
    def notify_exchange_request_created(self, req: BookExchangeRequest) -> object: ...
    def notify_transmission_request_created(self, req: BookExchangeRequest) -> object: ...
    def notify_exchange_request_accepted(self, req: BookExchangeRequest) -> object: ...
    def notify_exchange_request_rejected(self, req: BookExchangeRequest) -> object: ...
    def notify_exchange_request_cancelled(self, req: BookExchangeRequest) -> object: ...
    def notify_handoff_approved(self, handoff: LoanHandoff) -> None: ...
    def notify_handoff_given(self, handoff: LoanHandoff) -> None: ...
    def notify_handoff_cancelled(self, handoff: LoanHandoff) -> None: ...
    def notify_loan_transmitted(
        self,
        owner: CustomUser,
        previous_holder: CustomUser,
        new_holder: CustomUser,
        book_title: str,
        exchange_request: BookExchangeRequest | None = None,
    ) -> None: ...
    def notify_borrow_return_requested(self, shelf: Shelf) -> object: ...
    def notify_borrow_return_confirmed(
        self, lender: CustomUser, borrower: CustomUser, book_title: str
    ) -> object: ...
    def mark_return_notifications_read(
        self, lender: CustomUser, *, shelf_id: int, borrower_id: int, book_title: str
    ) -> int: ...


class CopyQueuePort(Protocol):
    def join_queue(self, user, copy, *, notify: bool = True, exchange_request=None): ...
    def leave_queue(self, user, copy_id: int): ...
    def after_copy_loaned_or_transmitted(self, copy_id: int, new_holder_id: int) -> None: ...
    def offer_next_after_return(self, copy_id: int, owner) -> object: ...
