# Generated by Django 6.0.3 on 2026-03-30 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=13, verbose_name='ISBN')),
                ('title', models.CharField(max_length=500, verbose_name='Назва')),
                ('authors', models.CharField(blank=True, max_length=500, verbose_name='Автори')),
                ('publisher', models.CharField(blank=True, max_length=300, verbose_name='Видавець')),
                ('publish_date', models.CharField(blank=True, max_length=64, verbose_name='Дата видання')),
                ('cover_url', models.URLField(blank=True, max_length=500, verbose_name='Обкладинка (URL)')),
                ('info_url', models.URLField(blank=True, max_length=500, verbose_name='Open Library')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'книга на полиці',
                'verbose_name_plural': 'книги на полиці',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'isbn'), name='unique_shelfbook_user_isbn')],
            },
        ),
    ]
