# Generated by Django 6.0.3 on 2026-03-30 09:28
# Додаємо Shelf.borrowed_from — позика: позичальник не може видалити книгу, лише повернути власнику.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_book_shelf_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='borrowed_from',
            field=models.ForeignKey(blank=True, help_text='Якщо заповнено - user є позичальником, книгу можна лише повернути, не видалити з полиці.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_lent_out', to=settings.AUTH_USER_MODEL, verbose_name='Позичено у'),
        ),
        migrations.AlterField(
            model_name='bookexchangerequest',
            name='shelf_owner',
            field=models.ForeignKey(help_text='Не змінюється після обміну (для історії).', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Власник на момент запиту'),
        ),
    ]
