# Generated by Django 4.2.29 on 2026-04-03 21:30
#
# Виправлено для Azure SQL: AlterField PK (BigAuto→Auto) ламав unique_shelf_user_book на Shelf.book_id (5074).
# Book/Shelf/... уже BigAuto у 0003/0001; Comment/Like додає 0005_avatarcollection_comment_like.
# Залишено порожні operations - міграція лише для гілки, яку зливає 0006_merge.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_shelf_borrowed_from'),
    ]

    operations = []
