# Generated by Django 6.0.3 on 2026-04-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_book_id_alter_bookexchangerequest_id_and_more'),
        ('mainApp', '0005_avatarcollection_comment_like'),
        ('mainApp', '0005_private_message'),
    ]

    operations = [
    ]
