# Generated by Django 6.0.3 on 2026-04-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_merge_shelf_and_avatar_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reader_age_brackets',
            field=models.JSONField(blank=True, default=list, help_text='Можна обрати кілька груп.', verbose_name='Рекомендована вікова група читача'),
        ),
    ]
