# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0019_copyevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_watched_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Головна відкривається на цьому пості для залогіненого користувача.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mainApp.post",
                verbose_name="Останній переглянутий пост",
            ),
        ),
    ]
