"""
Book cover text → title / authors / ISBN.

Primary: OCR.space (https://ocr.space/ocrapi) — POST multipart to parse/image.
Fallback: OpenAI-compatible vision (optional OPENAI_API_KEY).

Env:
  OCR_SPACE_API_KEY   — free tier key (header apikey)
  OCR_SPACE_LANGUAGE  — default auto (Cyrillic+Latin via Engine 3)
  OCR_SPACE_ENGINE    — default 3
  OPENAI_*            — optional vision fallback
"""
from __future__ import annotations

import base64
import io
import json
import logging
import os
import re
import uuid
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

logger = logging.getLogger("mainApp.book_cover_ai")

OCR_SPACE_URL = "https://api.ocr.space/parse/image"
# Free OCR.space key (override with OCR_SPACE_API_KEY). Kept as last-resort so
# QNAP containers that miss .env still recognize covers.
_DEFAULT_OCR_SPACE_KEY = "K89147673988957"
# Free plan: 1 MB per image
OCR_MAX_BYTES = 1024 * 1024
OCR_TARGET_BYTES = 980_000
MAX_EDGE = 1280

# Shown on shelf / recognize when cover has no catalog ISBN (local 9799… code).
NO_ISBN_NOTE = "ISBN code not exists"

_ISBN_RE = re.compile(
    r"(?:ISBN(?:-1[03])?[:\s]*)?"
    r"((?:97[89]\d{10})|(?:\d{9}[\dXx])|(?:\d[\d\-\s]{8,16}\d))",
    re.I,
)
_YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")
_AUTHOR_HINT = re.compile(
    r"^(автор(и|ка|ки)?|authors?|by|від|написав|написала)\s*[:\.]?\s*(.+)$",
    re.I | re.U,
)
_PUBLISHER_HINT = re.compile(
    r"(видавництво|видавн|publisher|press|publishing|edition|©|copyright|"
    r"издательство)",
    re.I | re.U,
)
_NOISE = re.compile(
    r"^(www\.|http|ocr\.|generated by|barcode|ean[\s\-]?13?)$",
    re.I,
)
_CYRILLIC_RE = re.compile(r"[\u0400-\u04FF]")

_PROMPT = """You are reading a photograph of a physical book cover.
Text may be Cyrillic (Ukrainian/Russian) and/or Latin.
Extract bibliographic fields visible on the cover. Respond with ONLY valid JSON:
{
  "title": "",
  "authors": "",
  "isbn": "",
  "publisher": "",
  "publish_date": ""
}
ISBN only if clearly visible (10 or 13 digits). Do not invent data.
Keep original language and script (do not transliterate).
If no ISBN is visible, leave isbn as empty string.
"""


class CoverAIError(Exception):
    def __init__(self, message: str, *, status: int = 400):
        super().__init__(message)
        self.message = message
        self.status = status


def _parse_env_file(path: Path) -> dict[str, str]:
    """Minimal .env reader (no python-dotenv required)."""
    out: dict[str, str] = {}
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return out
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        key = key.strip()
        val = val.strip().strip("'").strip('"')
        if key:
            out[key] = val
    return out


def _ensure_env_loaded() -> None:
    """Load .env on demand if OCR key still missing (Docker / late import)."""
    if (os.environ.get("OCR_SPACE_API_KEY") or "").strip():
        return
    for _blank in ("OCR_SPACE_API_KEY", "OPENAI_API_KEY", "OPENROUTER_API_KEY"):
        if _blank in os.environ and not (os.environ.get(_blank) or "").strip():
            del os.environ[_blank]

    paths = (
        Path("/app/.env"),
        Path(__file__).resolve().parent.parent / ".env",  # /app/.env or bookworms/.env
        Path(__file__).resolve().parent.parent.parent / ".env",
        Path.cwd() / ".env",
    )
    try:
        from dotenv import load_dotenv
    except ImportError:
        load_dotenv = None  # type: ignore

    for path in paths:
        if not path.is_file():
            continue
        if load_dotenv is not None:
            # Force OCR key from file over blank compose injection
            load_dotenv(path, override=True)
        else:
            for k, v in _parse_env_file(path).items():
                if k in (
                    "OCR_SPACE_API_KEY",
                    "OPENAI_API_KEY",
                    "OPENROUTER_API_KEY",
                    "OCR_SPACE_LANGUAGE",
                    "OCR_SPACE_ENGINE",
                    "OCR_SPACE_API_URL",
                ):
                    if v or k not in os.environ:
                        os.environ[k] = v
        if (os.environ.get("OCR_SPACE_API_KEY") or "").strip():
            return


def vision_configured() -> bool:
    """True if OCR.space and/or OpenAI vision is configured."""
    return bool(_ocr_space_key() or _openai_key())


def _ocr_space_key() -> str:
    _ensure_env_loaded()
    key = (os.environ.get("OCR_SPACE_API_KEY") or "").strip()
    if key:
        return key
    try:
        from django.conf import settings

        key = (getattr(settings, "OCR_SPACE_API_KEY", "") or "").strip()
        if key:
            return key
    except Exception:
        pass
    # Last resort: baked free-tier key so recognition works without env wiring
    return _DEFAULT_OCR_SPACE_KEY


def _openai_key() -> str:
    _ensure_env_loaded()
    key = (
        os.environ.get("OPENAI_API_KEY")
        or os.environ.get("OPENROUTER_API_KEY")
        or ""
    ).strip()
    if key:
        return key
    try:
        from django.conf import settings

        return (getattr(settings, "OPENAI_API_KEY", "") or "").strip()
    except Exception:
        return ""


def _ocr_language() -> str:
    # Engine 3 + auto handles mixed Cyrillic/Latin; override via env.
    return (os.environ.get("OCR_SPACE_LANGUAGE") or "auto").strip() or "auto"


def _ocr_engine() -> str:
    return (os.environ.get("OCR_SPACE_ENGINE") or "3").strip()


def _openai_base_url() -> str:
    return (
        os.environ.get("OPENAI_BASE_URL")
        or os.environ.get("OPENROUTER_BASE_URL")
        or "https://api.openai.com/v1"
    ).rstrip("/")


def _openai_model() -> str:
    return (
        os.environ.get("OPENAI_VISION_MODEL")
        or os.environ.get("OPENAI_MODEL")
        or "gpt-4o-mini"
    ).strip()


def _prepare_jpeg_bytes(uploaded, *, max_bytes: int = OCR_TARGET_BYTES) -> bytes:
    from PIL import Image

    raw = uploaded.read() if hasattr(uploaded, "read") else uploaded
    if isinstance(raw, memoryview):
        raw = raw.tobytes()
    if hasattr(uploaded, "seek"):
        try:
            uploaded.seek(0)
        except Exception:
            pass
    if not raw:
        raise CoverAIError("Порожнє зображення.", status=400)

    try:
        img = Image.open(io.BytesIO(raw))
        if img.mode != "RGB":
            img = img.convert("RGB")
        w, h = img.size
        if max(w, h) > MAX_EDGE:
            img.thumbnail((MAX_EDGE, MAX_EDGE), Image.Resampling.LANCZOS)
    except Exception as exc:
        logger.warning("cover_ai.prepare_fail exc=%s", exc)
        raise CoverAIError("Не вдалося прочитати зображення.", status=400) from exc

    for quality in (88, 82, 76, 70, 62, 55):
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=quality, optimize=True)
        data = buf.getvalue()
        if len(data) <= max_bytes:
            return data
    return data


def _multipart_image(jpeg: bytes, fields: dict[str, str]) -> tuple[bytes, str]:
    boundary = uuid.uuid4().hex
    parts: list[bytes] = []

    def add_field(name: str, value: str) -> None:
        parts.append(f"--{boundary}\r\n".encode())
        parts.append(f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode())
        parts.append(value.encode("utf-8"))
        parts.append(b"\r\n")

    for k, v in fields.items():
        add_field(k, v)

    parts.append(f"--{boundary}\r\n".encode())
    parts.append(
        b'Content-Disposition: form-data; name="file"; filename="cover.jpg"\r\n'
    )
    parts.append(b"Content-Type: image/jpeg\r\n\r\n")
    parts.append(jpeg)
    parts.append(f"\r\n--{boundary}--\r\n".encode())
    return b"".join(parts), f"multipart/form-data; boundary={boundary}"


def _call_ocr_space_once(jpeg: bytes, *, language: str, engine: str) -> str:
    key = _ocr_space_key()
    if not key:
        raise CoverAIError("OCR не налаштовано (OCR_SPACE_API_KEY).", status=503)
    if len(jpeg) > OCR_MAX_BYTES:
        raise CoverAIError(
            "Зображення завелике для OCR.space (макс. 1 МБ на безкоштовному плані).",
            status=400,
        )

    fields = {
        "language": language,
        "OCREngine": str(engine),
        "detectOrientation": "true",
        "scale": "true",
        "isOverlayRequired": "false",
        "filetype": "JPG",
    }
    body, content_type = _multipart_image(jpeg, fields)
    url = (os.environ.get("OCR_SPACE_API_URL") or OCR_SPACE_URL).strip()

    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "apikey": key,
            "Content-Type": content_type,
            "User-Agent": "DateDueSlip-OCR/1.0",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        err = ""
        try:
            err = exc.read().decode("utf-8", errors="replace")[:300]
        except Exception:
            pass
        logger.error("ocr_space.http status=%s body=%s", exc.code, err)
        raise CoverAIError(f"OCR.space недоступний (HTTP {exc.code}).", status=502) from exc
    except Exception as exc:
        logger.exception("ocr_space.request_fail")
        raise CoverAIError("Не вдалося звернутися до OCR.space.", status=502) from exc

    if payload.get("IsErroredOnProcessing"):
        msg = payload.get("ErrorMessage") or payload.get("ErrorDetails") or "OCR помилка"
        if isinstance(msg, list):
            msg = "; ".join(str(x) for x in msg)
        raise CoverAIError(str(msg)[:400], status=502)

    parsed = payload.get("ParsedResults") or []
    texts: list[str] = []
    for block in parsed:
        if not isinstance(block, dict):
            continue
        code = block.get("FileParseExitCode")
        if str(code) in ("1", "2") or code in (1, 2):
            t = (block.get("ParsedText") or "").strip()
            if t:
                texts.append(t)
    if not texts:
        err = ""
        if parsed and isinstance(parsed[0], dict):
            err = (parsed[0].get("ErrorMessage") or "")[:200]
        raise CoverAIError(err or "OCR не знайшов текст на зображенні.", status=422)
    return "\n".join(texts)


def _ocr_text_score(text: str) -> int:
    """Prefer real letter runs (Latin or Cyrillic) over barcode noise."""
    letters = sum(1 for c in text if c.isalpha())
    cyr = len(_CYRILLIC_RE.findall(text))
    return letters + cyr  # slight boost when Cyrillic present


def _call_ocr_space(jpeg: bytes) -> str:
    """
    Cyrillic (ukr/rus) and/or Latin covers.
    Engine 3 + language=auto is multi-script; then explicit ukr/rus/eng retries.
    """
    preferred = _ocr_language() or "auto"
    engine = _ocr_engine() or "3"
    attempts: list[tuple[str, str]] = []
    for lang, eng in (
        (preferred, engine),
        ("auto", "3"),
        ("ukr", "3"),
        ("rus", "3"),
        ("eng", "3"),
        ("ukr", "2"),
        ("rus", "2"),
        ("eng", "2"),
        ("auto", "2"),
    ):
        pair = (lang, str(eng))
        if pair not in attempts:
            attempts.append(pair)

    last_err: CoverAIError | None = None
    best = ""
    best_score = 0
    for lang, eng in attempts:
        try:
            text = _call_ocr_space_once(jpeg, language=lang, engine=eng)
            score = _ocr_text_score(text)
            if score >= 3:
                logger.info(
                    "ocr_space.ok lang=%s eng=%s chars=%s score=%s cyr=%s",
                    lang,
                    eng,
                    len(text),
                    score,
                    bool(_CYRILLIC_RE.search(text)),
                )
                return text
            if score > best_score or (score == best_score and len(text) > len(best)):
                best = text
                best_score = score
        except CoverAIError as exc:
            last_err = exc
            logger.warning("ocr_space.try_fail lang=%s eng=%s err=%s", lang, eng, exc.message)
            continue
    if best.strip():
        return best
    if last_err:
        raise last_err
    raise CoverAIError("OCR не знайшов текст на зображенні.", status=422)


def _extract_isbn(text: str) -> str:
    from .book_lookup import normalize_isbn

    for m in _ISBN_RE.finditer(text):
        norm = normalize_isbn(m.group(1))
        if norm:
            return norm
    return ""


def _clean_lines(text: str) -> list[str]:
    out: list[str] = []
    for raw in text.splitlines():
        line = re.sub(r"\s+", " ", raw).strip()
        if len(line) < 2:
            continue
        if _NOISE.search(line):
            continue
        if _ISBN_RE.fullmatch(line.replace(" ", "")) or line.upper().startswith("ISBN"):
            continue
        out.append(line)
    return out


def _parse_ocr_text(text: str) -> dict[str, str]:
    isbn = _extract_isbn(text)
    lines = _clean_lines(text)
    publisher = ""
    publish_date = ""
    authors = ""
    title = ""

    remaining: list[str] = []
    for line in lines:
        if _PUBLISHER_HINT.search(line) and not publisher:
            publisher = line[:300]
            continue
        m = _AUTHOR_HINT.match(line)
        if m and m.group(3):
            authors = m.group(3).strip()[:500]
            continue
        ym = _YEAR_RE.search(line)
        if ym and not publish_date and len(line) < 24:
            publish_date = ym.group(0)
        remaining.append(line)

    if not remaining:
        remaining = lines

    # Prefer top-of-cover lines for title (not only the longest line)
    if remaining:
        title = remaining[0][:500]
        if len(remaining) > 1:
            second = remaining[1]
            if second.lower() not in title.lower() and 3 <= len(second) <= 80:
                if not authors and 1 <= len(second.split()) <= 6:
                    authors = second[:500]
                elif len(second) >= 8:
                    title = f"{title} — {second}"[:500]

    if not authors and len(remaining) > 1:
        for cand in remaining[1:4]:
            words = cand.split()
            if 2 <= len(words) <= 6 and cand != title and not _PUBLISHER_HINT.search(cand):
                if not re.search(r"\d{4}", cand):
                    authors = cand[:500]
                    break

    # Last resort: keep raw OCR so the form is never empty after a successful read
    if not title.strip():
        compact = re.sub(r"\s+", " ", text).strip()
        if compact:
            title = compact[:500]

    return {
        "title": title.strip(),
        "authors": authors.strip(),
        "isbn": isbn,
        "publisher": publisher.strip(),
        "publish_date": publish_date.strip(),
        "raw_text": (text or "").strip()[:2000],
    }


def _normalize_result(raw: dict[str, Any]) -> dict[str, str]:
    title = str(raw.get("title") or "").strip()[:500]
    authors = str(raw.get("authors") or "").strip()[:500]
    publisher = str(raw.get("publisher") or "").strip()[:300]
    publish_date = str(raw.get("publish_date") or "").strip()[:64]
    isbn_raw = str(raw.get("isbn") or "").strip()
    if not isbn_raw:
        isbn_raw = _extract_isbn(" ".join([title, authors, publisher, isbn_raw]))
    else:
        from .book_lookup import normalize_isbn

        isbn_raw = normalize_isbn(isbn_raw) or _extract_isbn(isbn_raw) or ""
    return {
        "title": title,
        "authors": authors,
        "isbn": isbn_raw,
        "publisher": publisher,
        "publish_date": publish_date,
    }


def _chat_vision(jpeg: bytes) -> dict[str, Any]:
    key = _openai_key()
    if not key:
        raise CoverAIError("OpenAI vision не налаштовано.", status=503)

    b64 = base64.b64encode(jpeg).decode("ascii")
    url = f"{_openai_base_url()}/chat/completions"
    body = {
        "model": _openai_model(),
        "temperature": 0.1,
        "response_format": {"type": "json_object"},
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": _PROMPT},
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{b64}",
                            "detail": "high",
                        },
                    },
                ],
            }
        ],
    }
    req = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": "DateDueSlip-BookCoverAI/1.0",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    content = payload["choices"][0]["message"]["content"]
    if isinstance(content, list):
        content = "".join(
            part.get("text", "") if isinstance(part, dict) else str(part)
            for part in content
        )
    text = str(content).strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    parsed = json.loads(text)
    if not isinstance(parsed, dict):
        raise CoverAIError("AI повернув неочікуваний формат.", status=502)
    return parsed


def _enrich_from_catalog(fields: dict[str, str]) -> dict[str, str]:
    isbn = fields.get("isbn") or ""
    if not isbn:
        return fields
    try:
        from .book_lookup import fetch_book_by_isbn

        payload, _err = fetch_book_by_isbn(isbn, merge=True)
    except Exception:
        payload = None
    if not payload:
        return fields
    out = dict(fields)
    for key in ("title", "authors", "publisher", "publish_date"):
        if not (out.get(key) or "").strip():
            val = (payload.get(key) or "").strip()
            if val:
                out[key] = val
    cat_isbn = (payload.get("isbn") or "").strip()
    if cat_isbn:
        out["isbn"] = cat_isbn
    return out


def recognize_book_cover(uploaded) -> dict[str, Any]:
    """
    OCR cover image → bibliographic fields.
    OCR.space first; optional OpenAI vision if OCR text empty / failed and key set.
    """
    if not vision_configured():
        raise CoverAIError(
            "Розпізнавання не налаштовано (OCR_SPACE_API_KEY або OPENAI_API_KEY).",
            status=503,
        )

    jpeg = _prepare_jpeg_bytes(uploaded)
    source = "ocr.space"
    fields: dict[str, str] = {}
    ocr_err: CoverAIError | None = None

    if _ocr_space_key():
        try:
            text = _call_ocr_space(jpeg)
            fields = _parse_ocr_text(text)
            if not (fields.get("title") or "").strip() and not (fields.get("isbn") or "").strip():
                ocr_err = CoverAIError(
                    "OCR не знайшов назву чи ISBN на обкладинці.",
                    status=422,
                )
                fields = {}
        except CoverAIError as exc:
            ocr_err = exc
            fields = {}

    if not fields and _openai_key():
        try:
            raw = _chat_vision(jpeg)
            fields = _normalize_result(raw)
            source = "vision"
            ocr_err = None
        except Exception as exc:
            logger.warning("cover_ai.vision_fallback_fail %s", exc)
            if ocr_err:
                raise ocr_err
            raise CoverAIError("Не вдалося розпізнати обкладинку.", status=502) from exc
    elif ocr_err:
        raise ocr_err
    elif not fields:
        raise CoverAIError(
            "OCR не знайшов текст. Перевірте OCR_SPACE_API_KEY і чіткість фото.",
            status=422,
        )

    raw_text = fields.pop("raw_text", "")
    fields = _enrich_from_catalog(fields)
    fields["source"] = source
    if raw_text:
        fields["raw_text"] = raw_text
        fields["cover_text"] = raw_text
    isbn_ok = bool((fields.get("isbn") or "").strip())
    fields["isbn_missing"] = not isbn_ok
    fields["note"] = "" if isbn_ok else NO_ISBN_NOTE
    logger.info(
        "cover_ai.ok source=%s title=%r authors=%r isbn=%r note=%r",
        source,
        (fields.get("title") or "")[:40],
        (fields.get("authors") or "")[:40],
        fields.get("isbn") or "",
        fields.get("note") or "",
    )
    return fields


def _result_quality(fields: dict[str, Any]) -> int:
    """Score a recognition result: letter density + useful bibliographic fields."""
    raw = str(fields.get("raw_text") or fields.get("cover_text") or "")
    score = _ocr_text_score(raw)
    score += min(40, len(raw) // 15)
    if (fields.get("isbn") or "").strip():
        score += 80
    title = (fields.get("title") or "").strip()
    if title:
        score += 25 + min(40, len(title))
    if (fields.get("authors") or "").strip():
        score += 25
    if (fields.get("publisher") or "").strip():
        score += 10
    if (fields.get("publish_date") or "").strip():
        score += 5
    return score


def recognize_book_covers(uploads) -> dict[str, Any]:
    """
    OCR every uploaded cover photo, pick the best-quality result for
    bibliographic fields and «Текст з обкладинки» (raw_text / cover_text).
    """
    files = [f for f in (uploads or []) if f]
    if not files:
        raise CoverAIError("Потрібне хоча б одне фото обкладинки.", status=400)
    if len(files) == 1:
        out = recognize_book_cover(files[0])
        out["photos_scanned"] = 1
        out["photos_ok"] = 1
        out["best_photo_index"] = 0
        return out

    if not vision_configured():
        raise CoverAIError(
            "Розпізнавання не налаштовано (OCR_SPACE_API_KEY або OPENAI_API_KEY).",
            status=503,
        )

    candidates: list[tuple[int, int, dict[str, Any]]] = []
    errors: list[CoverAIError] = []
    for idx, uploaded in enumerate(files):
        try:
            fields = recognize_book_cover(uploaded)
            q = _result_quality(fields)
            candidates.append((idx, q, fields))
            logger.info(
                "cover_ai.multi idx=%s score=%s title=%r chars=%s",
                idx,
                q,
                (fields.get("title") or "")[:40],
                len(fields.get("raw_text") or ""),
            )
        except CoverAIError as exc:
            errors.append(exc)
            logger.warning("cover_ai.multi_fail idx=%s err=%s", idx, exc.message)

    if not candidates:
        if errors:
            raise errors[0]
        raise CoverAIError("OCR не знайшов текст на жодному фото.", status=422)

    candidates.sort(key=lambda row: (row[1], len(row[2].get("raw_text") or "")), reverse=True)
    best_idx, best_score, best = candidates[0]
    best = dict(best)

    # Fill missing bibliographic fields from other shots
    for _idx, _score, fields in candidates[1:]:
        for key in ("isbn", "title", "authors", "publisher", "publish_date"):
            if not (best.get(key) or "").strip() and (fields.get(key) or "").strip():
                best[key] = fields[key]

    raw = (best.get("raw_text") or best.get("cover_text") or "").strip()
    best["raw_text"] = raw
    best["cover_text"] = raw
    isbn_ok = bool((best.get("isbn") or "").strip())
    best["isbn_missing"] = not isbn_ok
    best["note"] = "" if isbn_ok else NO_ISBN_NOTE
    best["photos_scanned"] = len(files)
    best["photos_ok"] = len(candidates)
    best["best_photo_index"] = best_idx
    best["best_score"] = best_score
    logger.info(
        "cover_ai.multi_best idx=%s/%s score=%s title=%r",
        best_idx,
        len(files),
        best_score,
        (best.get("title") or "")[:40],
    )
    return best
