"""
Маршрути застосунку. Блок /library/… - бібліотека, полиці інших, обмін і позика.
Порядок важливий: спочатку "конкретні" шляхи (exchange/new), потім загальні (exchange/).
"""
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    home,
    activate,
    confirm_email_view,
    web3forms_bridge_view,
    contact_developers_view,
    notifications_inbox,
    notification_open_chat,
    notification_confirm_return,
    notifications_unread_count_view,
    CustomLoginView,
    CustomRegisterView,
    create_post,
    delete_post,
    edit_post,
    mark_post_watched,
    my_library,
    shared_library,
    recognize_book_cover_view,
    due_slips,
    unlock_shelf_reader_age_edit,
    update_manual_shelf_book,
    update_shelf_copy_listing,
    update_shelf_book_reader_age,
    remove_shelf_entry,
    library_bulk_action,
    refresh_book_price_view,
    return_borrowed_shelf_book,
    confirm_return_borrowed_shelf_book,
    browse_shelves,
    user_public_shelf,
    book_history,
    copy_history,
    create_exchange,
    exchange_requests,
    exchange_accept,
    exchange_propose_due,
    exchange_confirm_due,
    exchange_reject,
    exchange_cancel,
    handoff_cancel_view,
    handoff_confirm_give_view,
    handoff_confirm_receive_view,
    message_thread,
)
from .views import add_comment
from .views import toggle_like
from .isbn_scan_assets import isbn_scan_asset

urlpatterns = [
    path('', home, name='home'),
    # --- Бібліотека та обмін книгами ---
    path('library/', my_library, name='my_library'),
    path('library/shared/', shared_library, name='shared_library'),
    path(
        'library/recognize-cover/',
        recognize_book_cover_view,
        name='recognize_book_cover',
    ),
    # ISBN scanner assets (not /static/ — named volume can keep frozen old JS)
    path(
        "library/isbn-scan-assets/<str:name>",
        isbn_scan_asset,
        name="isbn_scan_asset",
    ),
    path('library/slips/', due_slips, name='due_slips'),
    path(
        'library/shelf/<int:shelf_id>/reader-age/',
        update_shelf_book_reader_age,
        name='update_shelf_book_reader_age',
    ),
    path(
        'library/shelf/<int:shelf_id>/reader-age/unlock/',
        unlock_shelf_reader_age_edit,
        name='unlock_shelf_reader_age_edit',
    ),
    path(
        'library/shelf/<int:shelf_id>/listing/',
        update_shelf_copy_listing,
        name='update_shelf_copy_listing',
    ),
    path(
        'library/shelf/<int:shelf_id>/edit/',
        update_manual_shelf_book,
        name='update_manual_shelf_book',
    ),
    path(
        'library/book/<int:book_id>/price/refresh/',
        refresh_book_price_view,
        name='refresh_book_price',
    ),
    path('library/remove/<int:shelf_id>/', remove_shelf_entry, name='remove_shelf_entry'),
    path('library/bulk/', library_bulk_action, name='library_bulk_action'),
    path('library/return/<int:shelf_id>/', return_borrowed_shelf_book, name='return_borrowed_shelf_book'),
    path(
        'library/confirm-return/<int:shelf_id>/',
        confirm_return_borrowed_shelf_book,
        name='confirm_return_borrowed_shelf_book',
    ),
    path('library/browse/', browse_shelves, name='browse_shelves'),
    path('library/user/<int:user_id>/', user_public_shelf, name='user_public_shelf'),
    path('library/book/<int:book_id>/history/', book_history, name='book_history'),
    path('library/copy/<int:copy_id>/history/', copy_history, name='copy_history'),
    path('library/exchange/new/', create_exchange, name='create_exchange'),
    path('library/exchange/', exchange_requests, name='exchange_requests'),
    path('library/exchange/<int:request_id>/accept/', exchange_accept, name='exchange_accept'),
    path(
        'library/exchange/<int:request_id>/propose-due/',
        exchange_propose_due,
        name='exchange_propose_due',
    ),
    path(
        'library/exchange/<int:request_id>/confirm-due/',
        exchange_confirm_due,
        name='exchange_confirm_due',
    ),
    path('library/exchange/<int:request_id>/reject/', exchange_reject, name='exchange_reject'),
    path('library/exchange/<int:request_id>/cancel/', exchange_cancel, name='exchange_cancel'),
    path(
        'library/handoff/<int:handoff_id>/give/',
        handoff_confirm_give_view,
        name='handoff_confirm_give',
    ),
    path(
        'library/handoff/<int:handoff_id>/receive/',
        handoff_confirm_receive_view,
        name='handoff_confirm_receive',
    ),
    path(
        'library/handoff/<int:handoff_id>/cancel/',
        handoff_cancel_view,
        name='handoff_cancel',
    ),
    path('messages/<int:partner_id>/', message_thread, name='message_thread'),
    path('notifications/', notifications_inbox, name='notifications_inbox'),
    path(
        'notifications/count/',
        notifications_unread_count_view,
        name='notifications_unread_count',
    ),
    path(
        'notifications/<int:message_id>/open/',
        notification_open_chat,
        name='notification_open_chat',
    ),
    path(
        'notifications/<int:message_id>/confirm-return/',
        notification_confirm_return,
        name='notification_confirm_return',
    ),
    path('contact/', contact_developers_view, name='contact_developers'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('register/confirm-email/', confirm_email_view, name='confirm_email'),
    path(
        'register/send-web3forms/<str:token>/',
        web3forms_bridge_view,
        name='web3forms_bridge',
    ),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate'),
    path('posts/create/', create_post, name='create_post'),
    path('posts/delete/<int:post_id>/', delete_post, name='delete_post'),
    path('posts/edit/<int:post_id>/', edit_post, name='edit_post'),
    path('posts/<int:post_id>/comment/', add_comment, name='add_comment'),
    path('posts/<int:post_id>/like/', toggle_like, name='toggle_like'),
    path('posts/<int:post_id>/watched/', mark_post_watched, name='mark_post_watched'),
]
