from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from . import views

urlpatterns = [
    path("health/", views.health),
    path("auth/register/", views.register),
    path("auth/check-availability/", views.check_registration_availability),
    path("auth/login/", views.login_view),
    path("auth/refresh/", TokenRefreshView.as_view()),
    path("auth/me/", views.me),
    path("contact/config/", views.contact_config),
    path("posts/", views.post_list),
    path("books/", views.book_search),
    path("posts/create/", views.post_create),
    path("posts/<int:post_id>/", views.post_detail),
    path("posts/<int:post_id>/like/", views.post_like),
    path("posts/<int:post_id>/comments/", views.post_comment),
    path("posts/<int:post_id>/watched/", views.post_mark_watched),
    path("shelf/", views.my_shelf),
    path("shelf/isbn/", views.shelf_add_isbn),
    path("shelf/manual/", views.shelf_add_manual),
    path("shelf/recognize-cover/", views.shelf_recognize_cover),
    path("shelf/bulk/", views.shelf_bulk),
    path("shelf/<int:shelf_id>/manual/", views.shelf_update_manual),
    path("books/<int:book_id>/price/refresh/", views.book_price_refresh),
    path("books/<int:book_id>/metadata/refresh/", views.book_metadata_refresh),
    path("shelf/<int:shelf_id>/", views.shelf_remove),
    path("shelf/<int:shelf_id>/reader-age/", views.shelf_reader_age),
    path("shelf/<int:shelf_id>/listing/", views.shelf_listing),
    path("shelf/<int:shelf_id>/return/", views.shelf_return),
    path("shelf/<int:shelf_id>/confirm-return/", views.shelf_confirm_return),
    path("slips/", views.due_slips),
    path("browse/", views.browse_shelves),
    path("users/<int:user_id>/shelf/", views.user_shelf),
    path("books/<int:book_id>/", views.book_detail),
    path("copies/<int:copy_id>/history/", views.copy_history),
    path("copies/<int:copy_id>/queue/", views.copy_queue_list),
    path("copies/<int:copy_id>/queue/join/", views.copy_queue_join),
    path("copies/<int:copy_id>/queue/leave/", views.copy_queue_leave),
    path("copies/<int:copy_id>/qr/ensure/", views.copy_qr_ensure_api),
    path("copies/<int:copy_id>/qr/attach/", views.copy_qr_attach_api),
    path("copies/<int:copy_id>/qr/rotate/", views.copy_qr_rotate_api),
    path("copies/qr/resolve/", views.copy_qr_resolve_api),
    path("copies/qr/print-labels/", views.copy_qr_print_labels_api),
    path("queue/mine/", views.my_queues),
    path("exchanges/", views.exchange_list),
    path("exchanges/create/", views.exchange_create),
    path("exchanges/<int:request_id>/accept/", views.exchange_accept_view),
    path("exchanges/<int:request_id>/offerable/", views.exchange_offerable_view),
    path("exchanges/<int:request_id>/pick-offer/", views.exchange_pick_offer_view),
    path("exchanges/<int:request_id>/propose-due/", views.exchange_propose_due_view),
    path("exchanges/<int:request_id>/confirm-due/", views.exchange_confirm_due_view),
    path("exchanges/<int:request_id>/reject/", views.exchange_reject_view),
    path("exchanges/<int:request_id>/cancel/", views.exchange_cancel_view),
    path("handoffs/<int:handoff_id>/give/", views.handoff_confirm_give),
    path("handoffs/<int:handoff_id>/receive/", views.handoff_confirm_receive),
    path("handoffs/<int:handoff_id>/cancel/", views.handoff_cancel),
    path("messages/partners/", views.message_partners),
    path("messages/<int:partner_id>/", views.message_thread),
    path("notifications/", views.notifications_list),
    path("notifications/unread-count/", views.notifications_unread_count),
    path("notifications/mark-read/", views.notifications_mark_read),
    path("library/", views.library_mine),
    path("library/invite/", views.library_invite),
    path("library/merge-code/generate/", views.library_merge_code_generate),
    path("library/merge-code/redeem/", views.library_merge_code_redeem),
    path("library/invite/<int:invite_id>/cancel/", views.library_invite_cancel),
    path("library/invite/<int:invite_id>/reject/", views.library_invite_reject),
    path("library/invite/<int:invite_id>/accept/", views.library_invite_accept),
    path(
        "library/invite/<int:invite_id>/confirm-isbn/",
        views.library_invite_confirm_isbn,
    ),
    path("library/actions/<int:action_id>/resolve/", views.library_action_resolve),
    path("library/split/", views.library_split_leave),
    path("library/election/start/", views.library_election_start),
    path("library/election/<int:election_id>/vote/", views.library_election_vote),
    path("library/election/<int:election_id>/finalize/", views.library_election_finalize),
    path("library/election/<int:election_id>/cancel/", views.library_election_cancel),
]
